tap 'homebrew/bundle'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'ansible'
brew 'cask'
brew 'coreutils'
brew 'cowsay'
brew 'curl'
brew 'editorconfig'
# brew 'emacs'
brew 'figlet'
brew 'fortune'
brew 'git'
brew 'git-lfs'
brew 'global', args: ['with-pygments', 'with-ctags']
brew 'htop-osx'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'lesspipe', args: ['with-syntax-highlighting']
brew 'nginx'
brew 'nodenv'
brew 'openssl'
brew 'phantomjs'
brew 'rbenv'
brew 'rcm'
brew 'reattach-to-user-namespace'
brew 'screenfetch'
brew 'ssh-copy-id'
brew 'stow'
brew 'stunnel'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'vim'
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'zsh'

cask '1password'
# cask 'battle-net'
cask 'cisco-spark'
cask 'discord'
cask 'doxie'
cask 'dropbox'
cask 'emacs'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'hipchat'
cask 'kindle'
cask 'launchbar'
# cask 'league-of-legends'
cask 'macvim'
cask 'rowanj-gitx'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
# cask 'steam'
cask 'vlc'
