tap 'homebrew/bundle'

brew 'ansible'
brew 'cask'
brew 'coreutils'
brew 'cowsay'
brew 'curl'
brew 'editorconfig'
brew 'emacs'
brew 'figlet'
brew 'fortune'
brew 'git'
brew 'git-lfs'
brew 'htop'
brew 'lolcat'
brew 'openssl'
brew 'rcm'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'screenfetch'
brew 'ssh-copy-id'
brew 'source-highlight'
brew 'stow'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'zsh'

# Latex
cask 'emacs'
cask 'finicky'
cask 'mactex'

# Fonts
cask 'font-hack-nerd-font'
cask 'font-sauce-code-pro-nerd-font'
